// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"

	"frank/app/dto"
)

type ContextEntry struct {
	ID      string
	Created time.Time
	Tags    []string
	Text    string
}

type Migration struct {
	ID      string
	Applied time.Time
}

type Prompt struct {
	ID      int64
	Created time.Time
	Data    []byte
}

type ScheduledJob struct {
	Name    string
	Created time.Time
	Data    dto.ScheduledJobData
}
