// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"

	"frank/app/dto"
)

type Migration struct {
	ID      string
	Applied time.Time
}

type ScheduledJob struct {
	Name    string
	Created time.Time
	Data    dto.ScheduledJobData
}
