// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package database

import (
	"context"
	"time"

	"frank/app/dto"
)

const countScheduledJobs = `-- name: CountScheduledJobs :one
SELECT COUNT(*) FROM scheduled_jobs
`

// CountScheduledJobs
//
//	SELECT COUNT(*) FROM scheduled_jobs
func (q *Queries) CountScheduledJobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countScheduledJobs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMigration = `-- name: CreateMigration :one
INSERT INTO migration (id, applied)
VALUES ($1, $2) RETURNING id
`

type CreateMigrationParams struct {
	ID      string
	Applied time.Time
}

// CreateMigration
//
//	INSERT INTO migration (id, applied)
//	VALUES ($1, $2) RETURNING id
func (q *Queries) CreateMigration(ctx context.Context, arg CreateMigrationParams) (string, error) {
	row := q.db.QueryRow(ctx, createMigration, arg.ID, arg.Applied)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createScheduledJob = `-- name: CreateScheduledJob :exec
INSERT INTO scheduled_jobs (name, created, data)
VALUES ($1, $2, $3)
`

type CreateScheduledJobParams struct {
	Name    string
	Created time.Time
	Data    dto.ScheduledJobData
}

// CreateScheduledJob
//
//	INSERT INTO scheduled_jobs (name, created, data)
//	VALUES ($1, $2, $3)
func (q *Queries) CreateScheduledJob(ctx context.Context, arg CreateScheduledJobParams) error {
	_, err := q.db.Exec(ctx, createScheduledJob, arg.Name, arg.Created, arg.Data)
	return err
}

const deleteScheduledJob = `-- name: DeleteScheduledJob :exec
DELETE FROM scheduled_jobs
WHERE name = $1
`

// DeleteScheduledJob
//
//	DELETE FROM scheduled_jobs
//	WHERE name = $1
func (q *Queries) DeleteScheduledJob(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deleteScheduledJob, name)
	return err
}

const getMigrations = `-- name: GetMigrations :many
SELECT id, applied
FROM migration
ORDER BY id
`

// GetMigrations
//
//	SELECT id, applied
//	FROM migration
//	ORDER BY id
func (q *Queries) GetMigrations(ctx context.Context) ([]Migration, error) {
	rows, err := q.db.Query(ctx, getMigrations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Migration{}
	for rows.Next() {
		var i Migration
		if err := rows.Scan(&i.ID, &i.Applied); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScheduledJob = `-- name: GetScheduledJob :one
SELECT name, created, data FROM scheduled_jobs
WHERE name = $1
`

// GetScheduledJob
//
//	SELECT name, created, data FROM scheduled_jobs
//	WHERE name = $1
func (q *Queries) GetScheduledJob(ctx context.Context, name string) (ScheduledJob, error) {
	row := q.db.QueryRow(ctx, getScheduledJob, name)
	var i ScheduledJob
	err := row.Scan(&i.Name, &i.Created, &i.Data)
	return i, err
}

const listScheduledJobs = `-- name: ListScheduledJobs :many
SELECT name, created, data FROM scheduled_jobs
ORDER BY created DESC
`

// ListScheduledJobs
//
//	SELECT name, created, data FROM scheduled_jobs
//	ORDER BY created DESC
func (q *Queries) ListScheduledJobs(ctx context.Context) ([]ScheduledJob, error) {
	rows, err := q.db.Query(ctx, listScheduledJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduledJob{}
	for rows.Next() {
		var i ScheduledJob
		if err := rows.Scan(&i.Name, &i.Created, &i.Data); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
