// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"context"

	"frank/app/dto"
)

type Querier interface {
	//CountScheduledJobs
	//
	//  SELECT COUNT(*) FROM scheduled_jobs
	CountScheduledJobs(ctx context.Context) (int64, error)
	//CreateContextEntry
	//
	//  INSERT INTO context_entries (created, tags, text)
	//  VALUES ($1, $2, $3) RETURNING id
	CreateContextEntry(ctx context.Context, arg CreateContextEntryParams) (int64, error)
	//CreateMigration
	//
	//  INSERT INTO migration (id, applied)
	//  VALUES ($1, $2) RETURNING id
	CreateMigration(ctx context.Context, arg CreateMigrationParams) (string, error)
	//CreateScheduledJob
	//
	//  INSERT INTO scheduled_jobs (data)
	//  VALUES ($1)
	//      RETURNING id
	CreateScheduledJob(ctx context.Context, data dto.ScheduledJobData) (int64, error)
	//DeleteContextEntry
	//
	//  DELETE
	//  FROM context_entries
	//  WHERE id = $1
	DeleteContextEntry(ctx context.Context, id int64) error
	//DeleteScheduledJob
	//
	//  DELETE FROM scheduled_jobs
	//  WHERE id = $1
	DeleteScheduledJob(ctx context.Context, id int64) error
	//GetContextEntry
	//
	//  SELECT id, created, tags, text
	//  FROM context_entries
	//  WHERE id = $1
	GetContextEntry(ctx context.Context, id int64) (ContextEntry, error)
	//GetMigrations
	//
	//  SELECT id, applied
	//  FROM migration
	//  ORDER BY id
	GetMigrations(ctx context.Context) ([]Migration, error)
	//GetScheduledJob
	//
	//  SELECT id, data FROM scheduled_jobs
	//  WHERE id = $1
	GetScheduledJob(ctx context.Context, id int64) (ScheduledJob, error)
	//ListContextEntries
	//
	//  SELECT id, created, tags, text
	//  FROM context_entries
	//  ORDER BY created DESC
	ListContextEntries(ctx context.Context) ([]ContextEntry, error)
	//ListContextEntriesByAnyTag
	//
	//  SELECT id, created, tags, text
	//  FROM context_entries
	//  WHERE tags && $1
	//  ORDER BY created DESC
	ListContextEntriesByAnyTag(ctx context.Context, tags []string) ([]ContextEntry, error)
	//ListContextEntriesByTags
	//
	//  SELECT id, created, tags, text
	//  FROM context_entries
	//  WHERE tags @> $1
	//  ORDER BY created DESC
	ListContextEntriesByTags(ctx context.Context, tags []string) ([]ContextEntry, error)
	//ListScheduledJobs
	//
	//  SELECT id, data FROM scheduled_jobs
	//  ORDER BY id
	ListScheduledJobs(ctx context.Context) ([]ScheduledJob, error)
}

var _ Querier = (*Queries)(nil)
